package com.ygy.model;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.uid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cateName
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private String catename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cid
     *
     * @return the value of category.cid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cid
     *
     * @param cid the value for category.cid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.uid
     *
     * @return the value of category.uid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.uid
     *
     * @param uid the value for category.uid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cateName
     *
     * @return the value of category.cateName
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public String getCatename() {
        return catename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cateName
     *
     * @param catename the value for category.cateName
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setCatename(String catename) {
        this.catename = catename;
    }
}