package com.ygy.model;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commId
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private Integer commid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.eid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commName
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private String commname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commText
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private String commtext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.reply
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private String reply;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commId
     *
     * @return the value of comment.commId
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public Integer getCommid() {
        return commid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commId
     *
     * @param commid the value for comment.commId
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setCommid(Integer commid) {
        this.commid = commid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.eid
     *
     * @return the value of comment.eid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.eid
     *
     * @param eid the value for comment.eid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commName
     *
     * @return the value of comment.commName
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public String getCommname() {
        return commname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commName
     *
     * @param commname the value for comment.commName
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setCommname(String commname) {
        this.commname = commname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commText
     *
     * @return the value of comment.commText
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public String getCommtext() {
        return commtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commText
     *
     * @param commtext the value for comment.commText
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setCommtext(String commtext) {
        this.commtext = commtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.reply
     *
     * @return the value of comment.reply
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.reply
     *
     * @param reply the value for comment.reply
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setReply(String reply) {
        this.reply = reply;
    }
}