package com.ygy.model;

import java.io.Serializable;

public class Essay implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.eid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.uid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.cid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.title
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.text
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.hit
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private Integer hit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.eid
     *
     * @return the value of essay.eid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.eid
     *
     * @param eid the value for essay.eid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.uid
     *
     * @return the value of essay.uid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.uid
     *
     * @param uid the value for essay.uid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.cid
     *
     * @return the value of essay.cid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.cid
     *
     * @param cid the value for essay.cid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.title
     *
     * @return the value of essay.title
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.title
     *
     * @param title the value for essay.title
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.text
     *
     * @return the value of essay.text
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.text
     *
     * @param text the value for essay.text
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.hit
     *
     * @return the value of essay.hit
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public Integer getHit() {
        return hit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.hit
     *
     * @param hit the value for essay.hit
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setHit(Integer hit) {
        this.hit = hit;
    }
}