package com.ygy.model;

import java.io.Serializable;

public class T1 implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.id
     *
     * @mbggenerated Tue Jan 30 18:01:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.name
     *
     * @mbggenerated Tue Jan 30 18:01:08 CST 2018
     */
    private Integer name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1.id
     *
     * @return the value of t1.id
     *
     * @mbggenerated Tue Jan 30 18:01:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1.id
     *
     * @param id the value for t1.id
     *
     * @mbggenerated Tue Jan 30 18:01:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1.name
     *
     * @return the value of t1.name
     *
     * @mbggenerated Tue Jan 30 18:01:08 CST 2018
     */
    public Integer getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1.name
     *
     * @param name the value for t1.name
     *
     * @mbggenerated Tue Jan 30 18:01:08 CST 2018
     */
    public void setName(Integer name) {
        this.name = name;
    }
}