package com.ygy.model;

import javax.validation.constraints.NotNull;
import java.math.BigInteger;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    @NotNull
    private BigInteger userid;
    private Integer rid;

    public void setRid(Integer rid) {
        this.rid = rid;
    }

    public Integer getRid() {
        return rid;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.report
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private Integer report;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.date
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userid
     *
     * @return the value of user.userid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public BigInteger getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userid
     *
     * @param userid the value for user.userid
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setUserid(BigInteger userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.report
     *
     * @return the value of user.report
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public Integer getReport() {
        return report;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.report
     *
     * @param report the value for user.report
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setReport(Integer report) {
        this.report = report;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.date
     *
     * @return the value of user.date
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.date
     *
     * @param date the value for user.date
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    public void setDate(String date) {
        this.date = date;
    }
}