package com.ygy.mapper;

import com.ygy.model.Essay;
import com.ygy.model.EssayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.Page;

public interface EssayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    int countByExample(EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    int deleteByExample(EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    int insert(Essay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    int insertSelective(Essay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    List<Essay> selectByExample(EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    Essay selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") Essay record, @Param("example") EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    int updateByExample(@Param("record") Essay record, @Param("example") EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    int updateByPrimaryKeySelective(Essay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbggenerated Thu Feb 01 13:09:43 CST 2018
     */
    int updateByPrimaryKey(Essay record);
    Essay selectTitle(String title);
    List<Essay> selectAllEssay();
    List<Essay> findByPage();
    Essay findById(int eid);
}